---
title: "lyme project"
output: html_document
date: "2023-08-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Following this paper: https://doi.org/10.1016/j.ecocom.2013.11.003

```{r}
require(deSolve)

mod1=function(t, y, parms){
  #Pull state variables from y vector
  L = y[1]
  N = y[2]
  A = y[3]
  Ri = y[4]
  Ni = y[5]
  Ai = y[6]
  
  #Pull the required parameter values from the parms vector
  R=parms["R"]
  D=parms["D"]
  f_a=parms["f_a"]
  f_l=parms["f_l"]
  f_n=parms["f_n"]
  b=parms["b"]
  K=parms["K"]
  mu_l=parms["mu_l"]
  mu_n=parms["mu_n"]
  mu_a=parms["mu_a"]
  mu_r=parms["mu_r"]
  beta_r=parms["beta_r"]
  beta_l=parms["beta_l"]
  beta_n=parms["beta_n"]
  
  dL = (b*f_a - 1/K*A)*A - (f_l + mu_l)*L
  dN = f_l*L - (mu_n + f_n)*N
  dA = f_n*N - mu_a*A
  dRi = beta_r*f_n*((R - Ri)/R)*N - mu_r*Ri
  dNi = beta_l*f_l*(Ri/R)*L - (f_n + mu_n)*Ni
  dAi = f_n*Ni + beta_n*f_n*(N - Ni)*(Ri/R) - mu_a*Ai
  
  res=c(dL, dN, dA, dRi, dNi, dAi)
  list(res)
}

#r_tick = b*f_a*(f_l/(f_l+mu_l))*(f_n/(mu_n+f_n))*(1/mu_a)
```

testing value of r0 for different rodent population size:
```{r}
R=10000 #total number of rodents
D=50 #total number of deer
#f_a=p1 #rate at which adult ticks attack deers
#f_l=p2 #rate at whihc larval ticks attach on rodents
#f_n=p3 #rate at which nymphal ticks bite rodents
b=600 #larvae hatching per adult tick-deer interaction
K=100 #scale of self regulation in tick reproduction
mu_l=0.7 #larva death rate
mu_n=0.8 #nymph death rate
mu_r=0.2 #rodent death rate
mu_a=1 #adult death rate
beta_r=0.3 #transmission rate to rodents
beta_l=0.6 #transmission rate to larval ticks
beta_n=0.6

##### frequency dependent seeking rate #####
r_tick_freq = b*f_a*(f_l/(f_l+mu_l))*(f_n/(mu_n+f_n))*(1/mu_a) 
print(r_tick_freq)

# we have f_l, f_n f_a = p1, p2, p3
p1= 0.1
p2= 0.1
p3= 0.5

f_a=p1 #rate at which adult ticks attack deers
f_l=p2 #rate at whihc larval ticks attach on rodents
f_n=p3 #rate at which nymphal ticks bite rodents

# to control disease, increase rodent population such that R_0 <= 1
# need R >= the eq below:

min_rat_pop = (beta_r*beta_l*mu_a/mu_r)*K*(b*p3-(p1 + mu_l)*((mu_n+p2)/p1)*(mu_a/p2))
#print(c("Minimum rat population size:", min_rat_pop))

A_eq = K*(b*f_a - ((mu_n + f_n)/f_l)* (mu_a/f_n)*(f_l+mu_l))
L_eq = (mu_n + f_n)/(f_l) * (mu_a/f_n)*A_eq
N_eq = mu_a/f_n *A_eq

#print(c("A*:", A_eq, "L*:", L_eq, "N*:", N_eq))

R_0 = sqrt((beta_r*beta_l*mu_a*A_eq)/(mu_r*R))
#print(c("R0:",R_0))

##### density-dependent seeking rate #####

q1=0.0006
q2=0.0006
q3=0.002
  
f_l = q1*R
f_n= q2*R
f_a= q3*D

r_tick_dens = b*q3*D* ((q1*R)/(q1*R + mu_l)) * ((q2*R)/(q2*R + mu_n)) * (1/mu_a)
print(c("Rtick:",r_tick_dens))

# require D > mu_a/(b*q3)

min_deer_pop = mu_a/(b*q3)
print(c("Min deer pop:", min_deer_pop))

min_rodent_pop2 = (2*mu_l*(mu_n/(q1*q2)))/(-(mu_l/q1 + mu_n/q2) 
                                           + sqrt((mu_l/q1 + mu_n/q2)^2 
                                                  + 4*(mu_l*mu_n)/(q1*q2) * ((b*q3*D)/(mu_a)-1
                                                                             )
                                                  )
                                           )
                                           
print(c("Minimum rodent pop:", min_rodent_pop2))

A_eq2 = K*(b*q3 - ((mu_n + f_n)/f_l)* (mu_a/f_n)*(f_l+mu_l))
L_eq2 = (mu_n + f_n)/(f_l) * (mu_a/f_n)*A_eq
N_eq2 = mu_a/(f_n) * A_eq

print(c("A*:", A_eq2, "L*:", L_eq2, "N*:", N_eq2))

R_0 = (beta_r*beta_l*mu_a*K)/(mu_r) * 
  ( (b*q3*D/R) - (mu_a/R)*
      (1 + 
         (mu_l/(q1*R))  
       ) *
      (1 + 
         (mu_n/(q2*R))
       )
   )
  
print(c("R0:",R_0))

```



```{r}
times  = seq(0, 10000, by=1)

parms= c(R=10000, #total number of rodents
  D=50, #total number of deer

  # if you want it density dependent, leave 0.1, 0.5, 0.5; 
  # if frequency dependent leave p1, p2, p3
  
  #f_a=p1, #rate at which adult ticks attack deers
  #f_l=p2, #rate at whihc larval ticks attach on rodents
  #f_n=p3, #rate at which nymphal ticks bite rodents
  f_a= 0.1, #rate at which adult ticks attack deers
  f_l= 0.5, #rate at whihc larval ticks attach on rodents
  f_n= 0.5, #rate at which nymphal ticks bite rodents


  b=600, #larvae hatching per adult tick-deer interaction
  K=100, #scale of self regulation in tick reproduction
  mu_l=0.7, #larva death rate
  mu_n=0.8, #nymph death rate
  mu_r=0.2, #rodent death rate
  mu_a=1, #adult death rate
  beta_r=0.3, #transmission rate to rodents
  beta_l=0.6, #transmission rate to larval ticks
  beta_n=0.6) #transmission rate to nymphal ticks
  
start = c(L=27000, N=10000, A=5000, Ri=3086, Ni=3981, Ai=3200) #start at eqiluilibria
```

VARYING PARAMETERS
```{r}
times  = seq(0, 1000, by=1)

R = rnorm(10, 10000, 10)
D = rnorm(10, 50, 1)

f_a = rnorm(10, 0.1, 0.001)
f_l = rnorm(10, 0.5, 0.002)
f_n = rnorm(10, 0.5, 0.002)

b = rnorm(10, 600, 1)
K = rnorm(10, 100, 0.1)
mu_l = rnorm(10, 0.7, 0.002)
mu_n = rnorm(10, 0.8, 0.002)
mu_r = rnorm(10, 0.2, 0.002)
mu_a = rep(1, 10)
beta_r = rnorm(10, 0.3, 0.002)
beta_l = rnorm(10, 0.6, 0.002)
beta_n = rnorm(10, 0.6, 0.002)

param_matrix = cbind(R, D, f_a, f_l, f_n, b, K, mu_l, mu_n, mu_r, mu_a, beta_r, beta_l, beta_n)
param_matrix


#parms= c(R=10000, #total number of rodents
#  D=50, #total number of deer

  # if you want it density dependent, leave 0.1, 0.5, 0.5; 
  # if frequency dependent leave p1, p2, p3
  
  #f_a=p1, #rate at which adult ticks attack deers
  #f_l=p2, #rate at whihc larval ticks attach on rodents
  #f_n=p3, #rate at which nymphal ticks bite rodents
#  f_a= 0.1, #rate at which adult ticks attack deers
#  f_l= 0.5, #rate at whihc larval ticks attach on rodents
#  f_n= 0.5, #rate at which nymphal ticks bite rodents


#  b=600, #larvae hatching per adult tick-deer interaction
#  K=100, #scale of self regulation in tick reproduction
#  mu_l=0.7, #larva death rate
#  mu_n=0.8, #nymph death rate
#  mu_r=0.2, #rodent death rate
#  mu_a=1, #adult death rate
#  beta_r=0.3, #transmission rate to rodents
#  beta_l=0.6, #transmission rate to larval ticks
#  beta_n=0.6) #transmission rate to nymphal ticks
  
#start = c(L=27000, N=10000, A=5000, Ri=3086, Ni=3981, Ai=3200) #start at eqiluilibria

```

```{r}

out = ode(y = start, times = times, func = mod1, 
          parms = param_matrix[1,])
out=as.data.frame(out)

t = out$time
max_L = out$L
min_L = out$L
max_N = out$N
min_N = out$N
max_A = out$A
min_A = out$A
max_Ri = out$Ri
min_Ri = out$Ri
max_Ni = out$Ni
min_Ni = out$Ni
max_Ai = out$Ai
min_Ai = out$Ai

stat_matrix = cbind(t, max_L, min_L, max_N, min_N, max_A, min_A, max_Ri, min_Ri, max_Ni, min_Ni, max_Ai, min_Ai)
stat_matrix = as.data.frame(stat_matrix)

for (i in 2:nrow(param_matrix)){
  
  out = ode(y = start, times = times, func = mod1, 
            parms = param_matrix[i,])
  out=as.data.frame(out)
  
  for (k in 1:nrow(out)){
    stat_matrix$max_L[k] = max(out$L[k], stat_matrix$max_L[k])
    stat_matrix$min_L[k] = min(out$L[k], stat_matrix$min_L[k])
    stat_matrix$max_N[k] = max(out$N[k], stat_matrix$max_N[k])
    stat_matrix$min_N[k] = min(out$N[k], stat_matrix$min_N[k])
    stat_matrix$max_A[k] = max(out$A[k], stat_matrix$max_A[k])
    stat_matrix$min_A[k] = min(out$A[k], stat_matrix$min_A[k])
    stat_matrix$max_Ri[k] = max(out$Ri[k], stat_matrix$max_Ri[k])
    stat_matrix$min_Ri[k] = min(out$Ri[k], stat_matrix$min_Ri[k])
    stat_matrix$max_Ni[k] = max(out$Ni[k], stat_matrix$max_Ni[k])
    stat_matrix$min_Ni[k] = min(out$Ni[k], stat_matrix$min_Ni[k])
    stat_matrix$max_Ai[k] = max(out$Ai[k], stat_matrix$max_Ai[k])
    stat_matrix$min_Ai[k] = min(out$Ai[k], stat_matrix$min_Ai[k])
  }
  
}

head(stat_matrix)

```
```{r}
plot(x = out$time, y = stat_matrix$min_L, col = "yellow", ylab = "Number of individuals", 
      xlab = "Time (days)", type = "l", xlim = c(0, 1000), ylim = c(0,30000))
 #lines(x = out$time, y = out$L, col = "yellow")
 lines(x = out$time, y = stat_matrix$min_N, col = "red")
 lines(x = out$time, y = stat_matrix$min_A, col = "purple")
 lines(x = out$time, y = stat_matrix$min_Ri, col = "magenta")
 lines(x = out$time, y = stat_matrix$min_Ni, col = "pink")
 lines(x = out$time, y = stat_matrix$min_Ai, col = "orange")
 
 lines(x = out$time, y = stat_matrix$max_L, col = "yellow")
 lines(x = out$time, y = stat_matrix$max_N, col = "red")
 lines(x = out$time, y = stat_matrix$max_A, col = "purple")
 lines(x = out$time, y = stat_matrix$max_Ri, col = "magenta")
 lines(x = out$time, y = stat_matrix$max_Ni, col = "pink")
 lines(x = out$time, y = stat_matrix$max_Ai, col = "orange")

#note that this figure is generated using simple plotting and not ggplot. 
#ggplot is a great R tool for plotting that you might want to look into. 
```

```{r}
D=50
  f_a=0.0006*100
  f_l=0.0006*100
  f_n=0.002*100
  b=600
  K=100
  mu_l=0.7
  mu_n=0.8
  mu_m=0.2
  mu_a=1
  beta_m=0.3
  beta_l=0.6
  beta_n=0.6

r_tick = b*f_a*(f_l/(f_l+mu_l))*(f_n/(mu_n+f_n))*(1/mu_a)
plot(r_tick, )
```
